apiVersion: v1
kind: ConfigMap
metadata:
 name: microservices-configmap
 namespace: development
data:
 DATABASE_URI: jdbc:mysql://mysql:3306/microservices?allowPublicKeyRetrieval=true&sslMode=DISABLED
 RABBITMQ_URI: rabbit.cloudamqp.com
