apiVersion: v1
kind: Secret
metadata:
 name: microservices-secrets
 namespace: development
type: Opaque
data:
 DATABASE_USER: cm9vdA==
 DATABASE_PASSWORD: Q2pHT0JQNDNLUg==
 RABBITMQ_USER: YWlmd3NiaHE=
 RABBITMQ_PASSWORD: YnVmWldhTnlTc2lDOEgwTjNOOEpHTmF5R251a0ViMks=
